### PR TITLE
Configure this project to alternatively run as a desktop application

### PR DESCRIPTION
**Pull request by zakpatterson**
Users that do not want to input their data into a website hosted elsewhere should be able to run this application as a desktop app.
 
scrots_img_010

I've added tauri to the project, which ships the rendered `index.html` for use in a webview. As of now, the final executable AppImage in linux is 3.7MB. Try it out!

### CODE REVIEW

**Comment by thegrims** [comment]
Wow, these changes look great! I'm impressed you were able to get all of this done so quickly. I'll do a test run after I have dinner tonight.

**Comment by thegrims** [comment]
@zakpatterson I'm seeing a blank window being rendered from the Tauri dev command running on Windows 10. Any thoughts on what could be the cause?
image

**Comment by thegrims** [comment]
Also is there a specific reason to use yarn over npm here?

**Comment by thegrims** [comment]
Got Tauri to compile, looks like the key was running `cargo install tauri-bundler --force`
https://github.com/tauri-apps/realworld/issues/2#issuecomment-592121535

**Comment by zakpatterson** [comment]
> Got Tauri to compile, looks like the key was running `cargo install tauri-bundler --force`
> [tauri-apps/realworld#2 (comment)](https://github.com/tauri-apps/realworld/issues/2#issuecomment-592121535)

Ah I was just about to reply, so the rendering looks good? Yes I've a few times had to delete the `src-tauri/target` folder to make sure cargo is compiling everything from start to finish at least once. Once you get up and running though you should find the auto-reloading is pretty neat.

**Comment by zakpatterson** [comment]
> Also is there a specific reason to use yarn over npm here?

I will remove yarn.lock and refer to both in the README. I prefer yarn but it's just a preference.

**Comment by thegrims** [comment]
Looks great! Thanks again for working on this, I considered making an electron app originally but this is even better. Merging now

**Comment by zakpatterson** [comment]
> Looks great! Thanks again for working on this, I considered making an electron app originally but this is even better. Merging now

The one caveat to be aware of with Tauri is that it uses Webview, so the compatibility is OS dependent. On Windows webview is rendered  by Edge, on linux it's done by GTK. So just like in browsers, the implementation of webstandard stuff is going to be a little different. For example CSS animations will render on linux and mac os but not windows most of the time. The experience will be the same as coding for Chrome and Edge, except all windows users will get the Edge experience. 

So that's the trade off as I see it, the executable is a hundred times smaller and faster, but you don't get the total packaged browser cross-platform compatibility.

Anyway, I hope I can figure out more to contribute!

**Comment by zakpatterson** [comment]
@thegrims this PR was merged as three commits when I expected it to be one. Consider changing the default merge strategy on github to be "Squash and Merge", so PRs can be merged as single commits by default.

**Comment by thegrims** [comment]
@zakpatterson Changed the default to squash and merge. I think going forwards I will squash and merge into development and potentially rebase onto master

**Comment by zakpatterson** [comment]
@thegrims I would suggest you just merge into master, and in the future just develop single features as PRs to be squashed merged into the master branch, and deploy from master. There's not really much value in my opinion to maintain a master branch as well as a quasi-master development branch.

**Comment by thegrims** [comment]
@zakpatterson Fair enough, I'll merge in your PR and merge the development -> master PR, Then I'll point Netlify at the master branch

**Pull request merged**
